name: websocket_project
description: A WebSocket server and client application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  path: ^1.8.0
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0